// Each project gets its own detail page at /projects/<id>.
// Image tags: big | medium | small | video. `isRight` floats a small image right.
const projects = [
  {
    id: 'project-1',
    title: 'Project One',
    img: '/projects/project-1/cover.webp',
    link: '/projects/project-1',
    date: '2024',
    liveLink: undefined,
    company: 'Client or Employer',
    primary: '#2D2D2D',
    accentColor: '#f0f4f1',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: '#c8b273',
    menuFontColor: '#f0f4f1',
    images: [
      { src: '/projects/project-1/1.webp', tag: 'big', isRight: false },
      { src: '/projects/project-1/2.webp', tag: 'small', isRight: false },
      { src: '/projects/project-1/3.webp', tag: 'small', isRight: true },
      { src: '/projects/project-1/4.webp', tag: 'big', isRight: false },
      { src: '/projects/project-1/5.webp', tag: 'medium', isRight: false },
      { src: '/projects/project-1/6.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'Open with the problem. What was broken, expensive or slow before you started?',
      'Then what you actually built, and which decisions mattered. Two or three sentences is plenty.',
      'Close with the result, or what you would do differently. Each string is its own paragraph.',
    ],
  },
  {
    id: 'project-2',
    title: 'Project Two',
    img: '/projects/project-2/cover.webp',
    link: '/projects/project-2',
    date: '2023',
    liveLink: undefined,
    company: 'Client or Employer',
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    images: [
      { src: '/projects/project-2/1.webp', tag: 'big', isRight: false },
      { src: '/projects/project-2/2.webp', tag: 'small', isRight: false },
      { src: '/projects/project-2/3.webp', tag: 'small', isRight: true },
      { src: '/projects/project-2/4.webp', tag: 'big', isRight: false },
      { src: '/projects/project-2/5.webp', tag: 'medium', isRight: false },
      { src: '/projects/project-2/6.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'Open with the problem. What was broken, expensive or slow before you started?',
      'Then what you actually built, and which decisions mattered. Two or three sentences is plenty.',
      'Close with the result, or what you would do differently. Each string is its own paragraph.',
    ],
  },
  {
    id: 'project-3',
    title: 'Project Three',
    img: '/projects/project-3/cover.webp',
    link: '/projects/project-3',
    date: '2022',
    liveLink: undefined,
    company: 'Client or Employer',
    primary: '#1f3a34',
    accentColor: '#f0f4f1',
    secondary: '#F4F7F5',
    fillColor: '#e1f2ea',
    menuColor: '#2f8a6a',
    menuFontColor: '#f0f4f1',
    images: [
      { src: '/projects/project-3/1.webp', tag: 'big', isRight: false },
      { src: '/projects/project-3/2.webp', tag: 'small', isRight: false },
      { src: '/projects/project-3/3.webp', tag: 'small', isRight: true },
      { src: '/projects/project-3/4.webp', tag: 'big', isRight: false },
      { src: '/projects/project-3/5.webp', tag: 'medium', isRight: false },
      { src: '/projects/project-3/6.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'Open with the problem. What was broken, expensive or slow before you started?',
      'Then what you actually built, and which decisions mattered. Two or three sentences is plenty.',
      'Close with the result, or what you would do differently. Each string is its own paragraph.',
    ],
  },
];
export default projects;
